apiVersion: v1
kind: Service
metadata:
  name: seq
  labels:
    app: {{ template "seq.name" . }}
    chart: {{ template "seq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 5341
      targetPort: ingestion
      protocol: TCP
      name: ingestion
  selector:
    app: {{ template "seq.name" . }}
    release: {{ .Release.Name }}
