replicaCount: 1
clustername: eshop-aks
pathBase: /seq

image:
  repository: datalust/seq
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
