{{- $name := include "basket-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  basket__ConnectionString: basket-data
  urls__IdentityUrl: http://identity-api
  all__EventBusConnection: rabbitmq
  all__InstrumentationKey: ""
  all__UseAzureServiceBus: "false"