{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "basket-api.fullname" . -}}
  {{- $ingressPath := include "pathBase" . -}}
  {{- $serviceName := $.Values.app.svc.basket -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "basket-api.fullname" . }}
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
    {{- end }}
    {{- if and .Values.inf.tls.enabled .Values.inf.tls.issuer }}
    cert-manager.io/issuer: {{ .Values.inf.tls.issuer }}
  {{- end }}
  {{- if .Values.inf.mesh.enabled }}
  {{- with .Values.ingress.mesh.annotations }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 80
  {{- end }}
{{- end }}
