apiVersion: v1
kind: Service
metadata:
  name: basket-api
  labels:
    app: {{ template "basket-api.name" . }}
    chart: {{ template "basket-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "basket-api.name" . }}
    release: {{ .Release.Name }}
