apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: resource-limits
spec:
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi