apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi