apiVersion: v1
kind: Service
metadata:
  name: mapping-service-deployment
  labels:
    app: mapping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapping-service
  template:
    metadata:
      labels:
        app: mapping-service
    spec:
      containers:
      - name: mapping-service-container
        image: adaptiveserviceplacement/mapping-service:latest
        env:
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq