{{- $ingressPath := include "pathBase" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apigwms.fullname" . }}
  labels:
    app: {{ template "apigwms.name" . }}
    chart: {{ template "apigwms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules: