apiVersion: v1
kind: Service
metadata:
  name: mobileshoppingapigw
  labels:
    app: {{ template "apigwms.name" . }}
    chart: {{ template "apigwms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: admin
      protocol: TCP
      name: admin     
  selector:
    app: {{ template "apigwms.name" . }}
    release: {{ .Release.Name }}
