{{- $name := include "webmvc.fullname" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webmvc.name" . }}
    chart: {{ template "webmvc.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: ""
  all__UseAzureServiceBus: "false"
  webmvc__keystore: keystore-data
  internalurls__apigwws: http://webshoppingapigw
  internalurls__identity__hc: http://identity-api/hc
  urls__apigwws: {{ $protocol }}://testapplication.com/webshoppingapigw
  urls__mvc: {{ $protocol }}://testapplication.com/webmvc
  urls__IdentityUrl: {{ $protocol }}://testapplication.com/identity
