{{- if .Values.ingress.enabled -}}
{{- $ingressPath := include "pathBase" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "webmvc.fullname" . }}
  labels:
    app: {{ template "webmvc.name" . }}
    chart: {{ template "webmvc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}


spec:
  defaultBackend:
    service:
      name: webmvc
      port:
        number: 80
{{- end }}