replicaCount: 1
clusterName: eshop-aks
pathBase: /migration-service

image:
  repository: adaptiveserviceplacement/migration-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  values:
    - name: SPRING_RABBITMQ_HOST
      value: rabbitmq
