apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  labels: 
    app: monitoring-service
    chart: monitoring-service-
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "monitoring-service.name" . }}
    release: {{ .Release.Name }}