{{- $name := include "catalog-api.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "catalog-api.name" . }}
    chart: {{ template "catalog-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  catalog__ConnectionString: Server={{ $sqlsrv }};Initial Catalog=CatalogDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true;
  catalog__PicBaseUrl: {{ $protocol }}://testapplication.com/webshoppingapigw/c/api/v1/catalog/items/[0]/pic/
  catalog__AzureStorageEnabled: "false"
  all__EventBusConnection: rabbitmq
  all__InstrumentationKey: ""
  all__UseAzureServiceBus: "false"