replicaCount: 1
clutername: ehop-aks
pathBase: /rabbit

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
