replicaCount: 1
clutername: ehop-aks
pathBase: /rabbit

image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5672

ingress:
  enabled: true
  annotations: {}
  hosts:
    - rabbitmq.example.com
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
