{{- $name := include "webhooks-web.fullname" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webhooks-web.name" . }}
    chart: {{ template "webhooks-web.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  urls__webhooks: {{ $protocol }}://testapplication.com/webhooks-api
  identity_e: {{ $protocol }}://testapplication.com/identity
  webhooksweb_e: {{ $protocol }}://testapplication.com/webhooks-web
  urls_webhooksweb: http://webhooks-client
