apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
spec:
  selector:
    matchLabels:
      app: monitoring-service
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
      - name: monitoring-service
        image: adaptiveserviceplacement/monitoring-service:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_DATABASE
          value: myapp_db
        imagePullSecrets:
        - name: myregistrykey
