{{- $name := include "migration-service.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "migration-service.fullname" . }}
  labels:
    ufo: {{ $cfgname}}
    app: {{ template "migration-service.name" . }}
    chart: {{ template "migration-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "migration-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "migration-service.name" . }}
        release: {{ .Release.Name }}
      {{ if .Values.inf.mesh.enabled -}}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}             
    spec:
      serviceAccountName: tiller
      {{ if .Values.inf.registry -}}
      imagePullSecrets:
      - name: {{ .Values.inf.registry.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}            
          image: "{{ template "fqdn-image" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATH_BASE
              value: {{ include "pathBase" . }}
            - name: k8sname
              value: {{ .Values.clusterName }}
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

