{{- if .Values.ingress.enabled -}}
{{- $fullName := include "webstatus.fullname" . -}}
{{- $ingressPath := include "pathBase" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "webstatus.fullname" . }}
  labels:
    app: {{ template "webstatus.name" . }}
    chart: {{ template "webstatus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}


spec:
  defaultBackend:
    service:
      name: webstatus
      port:
        number: 80        
{{- end }}