{{- $name := include "apigwws.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
{{- $envoycfgname := printf "%s-%s" "envoy" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apigwws.fullname" . }}
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "apigwws.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "apigwws.name" . }}
        release: {{ .Release.Name }}       
    spec:
      securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          fsGroup: 2000    
      volumes:
      - name: config
        configMap:
          name: {{ $envoycfgname }}
          items:
          - key: envoy.yaml
            path: envoy.yaml
      containers:
        - name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              port: 8001
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 8001
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 60
          image: "{{ template "fqdn-image" . }}:v1.21.0"
          imagePullPolicy:
          volumeMounts:
          - name: config
            mountPath: /etc/envoy
          env:
            - name: PATH_BASE
              value: {{ include "pathBase" . }}
            - name: k8sname
              value: {{ .Values.clusterName }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 8001
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

