apiVersion: v1
kind: Service
metadata:
  name: webshoppingapigw
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: ClusterIP
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: {{ template "apigwws.name" . }}
    release: {{ .Release.Name }}
