{{- $name := include "webspa.fullname" . -}}
{{- $mongo := include "mongo-name" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: ""
  webspa__keystore: keystore-data
  internalurls__apigwws: http://webshoppingapigw
  internalurls__identity__hc: http://identity-api/hc
  urls__apigwws: {{ $protocol }}://testapplication.com/webshoppingapigw
  urls__spa: {{ $protocol }}://testapplication.com
  urls__IdentityUrl: {{ $protocol }}://testapplication.com/identity