{{- $name := include "webspa.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}
{{- $spa := include "url-of" (list .Values.app.ingress.entries.spa .) -}}
{{- $mongo := include "mongo-name" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: ""
  webspa__keystore: keystore-data
  internalurls__apigwws: http://{{ .Values.app.svc.webshoppingapigw }}
  internalurls__identity__hc: http://identity-api/hc
  urls__apigwws: {{ $protocol }}://{{ $webshoppingapigw }}
  urls__spa: {{ $protocol }}://{{ $spa }}
  urls__IdentityUrl: {{ $protocol }}://{{ $identity }}