apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "rabbitmq.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: {{ template "rabbitmq.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq