name: Deploy Helm chart to GKE

inputs:
  zone:
    description: "Location of Kubernetes Cluster"
    required: true
  cluster_name:
    description: "Name of GKE cluster"
    required: true
  resource_group:
    description: "Resource group of GKE cluster"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  chart:
    description: "Chart name"
    required: true
  chart_root:
    description: "Root folder of chart"
    required: true
  namespace:
    description: "Namespace to deploy to"
    required: true
  values:
    description: "Values for Chart"
    required: true

runs:
  using: "composite"
  steps:
  - name: Authenticate with Google Cloud Platform
    uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
      version: '333.0.0'
      project_id: ${{ secrets.PROJECT_ID }}
      service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      service_account_key: ${{ secrets.GKE_SA_KEY }}
    id: auth

  - name: Configure kubectl
    uses: GoogleCloudPlatform/github-actions/setup-kubectl@master
    with:
      version: 'v1.22.0'
      project_id: ${{ secrets.PROJECT_ID }}
      location: ${{ inputs.zone }}
      cluster: ${{ inputs.cluster_name }}
    id: kubectl

  - name: Deploy Helm chart
    run: |
      helm upgrade --install \
        --namespace ${{ inputs.namespace }} \
        --values ${{ inputs.values }} \
        ${{ inputs.chart }} \
        .${{ inputs.chart_root }}
    env:
      KUBECONFIG: ${{ steps.kubectl.outputs.kubeconfig }}