{{- $name := include "identity-api.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "identity-api.name" . }}
    chart: {{ template "identity-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  identity__ConnectionString: Server={{ $sqlsrv }};Initial Catalog=IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true;
  identity__keystore: keystore-data
  all__InstrumentationKey: ""
  mvc_e: http://testapplication.com/webmvc
  spa_e: http://testapplication.com
  basket_e: http://testapplication.com/basket-api
  ordering_e: http://testapplication.com/ordering-api
  mobileshoppingagg_e: http://testapplication.com/mobileshoppingapigw
  webshoppingagg_e: http://testapplication.com/webshoppingagg
  xamarin_callback_e: http://testapplication.com/xamarin_callback
  webhooksapi_e:  http://testapplication.com/webhooks-api
  webhooksweb_e: http://testapplication.com/webhooks-web
  enableDevspaces: "{{ .Values.enableDevspaces }}"