rbac:
  create: true
  role:
    name: my-cluster-role
    rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "watch", "list"]
  binding:
    name: my-cluster-role-binding
    roleRef:
      kind: ClusterRole
      name: my-cluster-role
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: default