{{- $name := include "webshoppingagg.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webshoppingagg.name" . }}
    chart: {{ template "webshoppingagg.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: ""
  webshoppingagg__keystore: keystore-data
  internalurls__basket: http://basket-api
  internalurls__catalog: http://catalog-api
  internalurls__identity: http://identity-api
  internalurls__ordering: http://ordering-api
  internalurls__basket__hc: http://basket-api/hc
  internalurls__catalog__hc: http://catalog-api/hc
  internalurls__identity__hc: http://identity-api/hc
  internalurls__ordering__hc: http://ordering-api/hc
  internalurls__payment__hc: http://payment-api/hc
  internalurls__grpcBasket: "http://basket-api:{{ .Values.service.grpcPort }}"
  internalurls__grpcCatalog: "http://catalog-api:{{ .Values.service.grpcPort }}"
  internalurls__grpcOrdering: "http://ordering-api:{{ .Values.service.grpcPort }}"
  urls__IdentityUrlExternal: {{ $protocol }}://{{ $identity }}
