name: Deploy ordering-backgroundtasks

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  workflow_run:
    workflows: ["ordering-backgroundtasks"]
    branches: [dev]
    types: [completed]

env:
  CHART: ordering-backgroundtasks
  NAMESPACE: eshop
  CHART_ROOT: deploy/k8s/helm
  LOCATION: europe-west3-a
  VALUES: ./deploy/k8s/helm/ordering-backgroundtasks/values.yaml

jobs:
  deploy-to-k8s:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    #if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/deploy-helm
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          location: ${{ env.LOCATION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}
          values: ${{ env.VALUES }}
